// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuoteOfTheDay.Data;

namespace QuoteOfTheDay.Migrations
{
    [DbContext(typeof(QuoteOfTheDayDbContext))]
    partial class QuoteOfTheDayDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("QuoteOfTheDay.Entities.Quote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Quotes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Dr . Seuss",
                            Text = "You’re off to great places, today is your day. Your mountain is waiting, so get on your way."
                        },
                        new
                        {
                            Id = 2,
                            Author = "Groucho Marx",
                            Text = "No one is perfect - that’s why pencils have erasers."
                        },
                        new
                        {
                            Id = 3,
                            Author = "Wolfgang Riebe",
                            Text = "Marriage is the chief cause of divorce."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
